### ISSUE TITLE
README build instruction error

### ISSUE THREAD

**Issue by samuelyeungkc** [billylo1/covidpass#16]
Please see the attached stacktrace.
I followed the instruction by doing 
```
yarn install
yarn dev
```
Both of the command ran without issue.
When I attempt to connect to `http://localhost:3000/` the follow error occurred.
```
bash-mini: covidpass$ yarn install && yarn dev
yarn install v1.17.3
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 6.09s.
yarn run v1.17.3
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5

warn - You have enabled the JIT engine which is currently in preview.
warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.
event - compiled successfully
event - build page: /
wait  - compiling...
event - compiled successfully
sentry initialized
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
sentry initialized
/Users/user/Code/covidpass/node_modules/pdfjs-dist/build/pdf.js:2164
    if (arguments[0]?.annotationStorage !== undefined) {
                     ^

SyntaxError: Unexpected token '.'
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.pdfjs-dist (/Users/user/Code/covidpass/.next/server/pages/index.js:579:18)
    at __webpack_require__ (/Users/user/Code/covidpass/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/process.ts:6:68)
    at Object../src/process.ts (/Users/user/Code/covidpass/.next/server/pages/index.js:382:1)
    at __webpack_require__ (/Users/user/Code/covidpass/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./components/Form.tsx:17:70)
    at Object../components/Form.tsx (/Users/user/Code/covidpass/.next/server/pages/index.js:85:1)
    at __webpack_require__ (/Users/user/Code/covidpass/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.tsx:13:74)
    at Object../pages/index.tsx (/Users/user/Code/covidpass/.next/server/pages/index.js:316:1)
    at __webpack_require__ (/Users/user/Code/covidpass/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/user/Code/covidpass/.next/server/pages/index.js:643:52)
    at /Users/user/Code/covidpass/.next/server/pages/index.js:644:28
    at Object.<anonymous> (/Users/user/Code/covidpass/.next/server/pages/index.js:647:3)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at requirePage (/Users/user/Code/covidpass/node_modules/next/dist/next-server/server/require.js:1:1519)
    at loadComponents (/Users/user/Code/covidpass/node_modules/next/dist/next-server/server/load-components.js:1:1442)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async DevServer.findPageComponents (/Users/user/Code/covidpass/node_modules/next/dist/next-server/server/next-server.js:77:257)
    at async DevServer.renderToHTML (/Users/user/Code/covidpass/node_modules/next/dist/next-server/server/next-server.js:138:542)
    at async DevServer.renderToHTML (/Users/user/Code/covidpass/node_modules/next/dist/server/next-dev-server.js:36:578)
    at async DevServer.render (/Users/user/Code/covidpass/node_modules/next/dist/next-server/server/next-server.js:75:160)
    at async Object.fn (/Users/user/Code/covidpass/node_modules/next/dist/next-server/server/next-server.js:58:672)
    at async Router.execute (/Users/user/Code/covidpass/node_modules/next/dist/next-server/server/router.js:25:67)
    at async DevServer.run (/Users/user/Code/covidpass/node_modules/next/dist/next-server/server/next-server.js:68:1042)
    at async DevServer.handleRequest (/Users/user/Code/covidpass/node_modules/next/dist/next-server/server/next-server.js:32:504)
/Users/user/Code/covidpass/node_modules/pdfjs-dist/build/pdf.js:2164
    if (arguments[0]?.annotationStorage !== undefined) {
                     ^

SyntaxError: Unexpected token '.'
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.pdfjs-dist (/Users/user/Code/covidpass/.next/server/pages/index.js:579:18)
    at __webpack_require__ (/Users/user/Code/covidpass/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/process.ts:6:68)
    at Object../src/process.ts (/Users/user/Code/covidpass/.next/server/pages/index.js:382:1)
    at __webpack_require__ (/Users/user/Code/covidpass/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./components/Form.tsx:17:70)
    at Object../components/Form.tsx (/Users/user/Code/covidpass/.next/server/pages/index.js:85:1)
    at __webpack_require__ (/Users/user/Code/covidpass/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.tsx:13:74)
    at Object../pages/index.tsx (/Users/user/Code/covidpass/.next/server/pages/index.js:316:1)
    at __webpack_require__ (/Users/user/Code/covidpass/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/user/Code/covidpass/.next/server/pages/index.js:643:52)
    at /Users/user/Code/covidpass/.next/server/pages/index.js:644:28
    at Object.<anonymous> (/Users/user/Code/covidpass/.next/server/pages/index.js:647:3)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at requirePage (/Users/user/Code/covidpass/node_modules/next/dist/next-server/server/require.js:1:1519)
    at loadComponents (/Users/user/Code/covidpass/node_modules/next/dist/next-server/server/load-components.js:1:1442)
    at async DevServer.findPageComponents (/Users/user/Code/covidpass/node_modules/next/dist/next-server/server/next-server.js:77:257)
    at async DevServer.renderToHTML (/Users/user/Code/covidpass/node_modules/next/dist/next-server/server/next-server.js:138:542)
    at async DevServer.renderToHTML (/Users/user/Code/covidpass/node_modules/next/dist/server/next-dev-server.js:36:578)
    at async DevServer.render (/Users/user/Code/covidpass/node_modules/next/dist/next-server/server/next-server.js:75:160)
    at async Object.fn (/Users/user/Code/covidpass/node_modules/next/dist/next-server/server/next-server.js:58:672)
    at async Router.execute (/Users/user/Code/covidpass/node_modules/next/dist/next-server/server/router.js:25:67)
    at async DevServer.run (/Users/user/Code/covidpass/node_modules/next/dist/next-server/server/next-server.js:68:1042)
    at async DevServer.handleRequest (/Users/user/Code/covidpass/node_modules/next/dist/next-server/server/next-server.js:32:504)


```
Text file version: [stack.txt](https://github.com/billylo1/covidpass/files/7223222/stack.txt)

**Comment by puiiyuen** [comment]
I have the same problem.
Change
https://github.com/billylo1/covidpass/blob/884ba7bbeca3e5097bff0ecc7dfdd276884dadf9/package.json#L44
to `"pdfjs-dist": "2.5.207",` for a temporary solution

**Comment by straxus** [comment]
We've bumped the pdfjs-dist version to 2.6.347 - that should resolve this issue now
